// src/shared/ui/rating.tsx
import { Star } from "lucide-react";

export const Rating = ({ rating }: { rating?: number | null }) => {
  const stars = new Array(5).fill("");

  return (
    <div className='mt-1.5 mb-2 flex items-center gap-1'>
      {stars.map((i, index) => (
        <Star
          key={index}
          className={
            index >= (rating ?? 0)
              ? "fill-muted text-muted"
              : "fill-primary text-primary"
          }
        />
      ))}
    </div>
  );
};

// app/components/ui/Rating.vue
<script setup lang="ts">
defineProps(['rating']);
</script>

<template>
  <div class="mt-1.5 mb-2 flex items-center gap-1">
    <div v-for="i in 5">
      <UIcon v-if="i < (rating ?? 0)" name="mage:star-fill" class="size-5 fill-primary text-primary" />
      <UIcon v-else name="mage:star-fill" class="size-5 fill-muted text-muted" />
    </div>
  </div>
</template>
